name: CI

on:
  push:
    branches:
      - main
  pull_request:

env:
  NODE_VERSION: 14

jobs:
  lint:
    name: Lint files
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
      - run: npm install --frozen-lockfile
      - run: npm lint

  test:
    name: Test
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
      - run: npm install --frozen-lockfile
      - run: npm test